# Generated by Django 5.2.5 on 2025-08-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetoReclamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(max_length=50)),
                ('numero_documento', models.CharField(max_length=50)),
                ('tipo_objeto', models.CharField(max_length=50)),
                ('descripcion_objeto', models.TextField()),
                ('fecha_entrega', models.CharField()),
                ('telefono', models.CharField(max_length=20)),
                ('suministro_correo', models.BooleanField(default=False)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('responsable_entrega', models.CharField(max_length=100)),
            ],
        ),
    ]
