# Generated by Django 5.2.5 on 2026-08-29 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('icono', models.CharField(blank=True, default='', max_length=10, verbose_name='Seña (opcional)')),
                ('color', models.CharField(default='#4f46e5', max_length=7, verbose_name='Color (hex)')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='objetoreclamado',
            options={'ordering': ['-fecha_registro', '-id'], 'verbose_name': 'Objeto', 'verbose_name_plural': 'Objetos'},
        ),
        migrations.AddField(
            model_name='objetoreclamado',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('reclamado', 'Reclamado'), ('entregado', 'Entregado')], db_index=True, default='disponible', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='objetoreclamado',
            name='fecha_reclamo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del reclamo'),
        ),
        migrations.AddField(
            model_name='objetoreclamado',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='objetoreclamado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='objetos/', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='objetoreclamado',
            name='lugar_encontrado',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lugar donde fue encontrado'),
        ),
        migrations.AddField(
            model_name='objetoreclamado',
            name='nombre_objeto',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre del objeto'),
        ),
        migrations.AddField(
            model_name='objetoreclamado',
            name='reclamado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_reclamados', to=settings.AUTH_USER_MODEL, verbose_name='Reclamado por (usuario)'),
        ),
        migrations.AddField(
            model_name='objetoreclamado',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objetos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='objetoreclamado',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='objetoreclamado',
            name='descripcion_objeto',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='objetoreclamado',
            name='fecha_entrega',
            field=models.CharField(blank=True, max_length=100, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='objetoreclamado',
            name='nombre_persona',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre de quien reclama'),
        ),
        migrations.AlterField(
            model_name='objetoreclamado',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='objetoreclamado',
            name='responsable_entrega',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable de la entrega'),
        ),
        migrations.AlterField(
            model_name='objetoreclamado',
            name='suministro_correo',
            field=models.BooleanField(default=False, verbose_name='¿Suministró correo?'),
        ),
        migrations.AlterField(
            model_name='objetoreclamado',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='objetoreclamado',
            name='tipo_documento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='objetoreclamado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='objetos', to='registro_objetos.categoria', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PEP', 'Pasaporte')], max_length=10, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(blank=True, max_length=50, verbose_name='Número de documento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('programa', models.CharField(blank=True, max_length=120, verbose_name='Programa / Carrera')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuario',
            },
        ),
        migrations.CreateModel(
            name='SolicitudReclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, verbose_name='¿Por qué crees que es tuyo? (opcional)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de la solicitud')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='registro_objetos.objetoreclamado', verbose_name='Objeto')),
                ('respondida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_respondidas', to=settings.AUTH_USER_MODEL, verbose_name='Respondida por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Solicitud de reclamación',
                'verbose_name_plural': 'Solicitudes de reclamación',
                'ordering': ['-fecha'],
            },
        ),
    ]
