# Generated by Django 5.2.5 on 2026-08-29 23:41

from django.db import migrations, models


def limpiar_iconos(apps, schema_editor):
    """Sanea las señas heredadas: los emojis ya no forman parte del diseño."""
    Categoria = apps.get_model('registro_objetos', 'Categoria')
    Categoria.objects.exclude(icono='').update(icono='')


def revertir(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0004_remove_objetoreclamado_tipo_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#0b7a54', max_length=7, verbose_name='Color (hex)'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, default='', help_text='Abreviatura corta. Las fichas muestran las iniciales del nombre.', max_length=10, verbose_name='Seña (opcional)'),
        ),
        migrations.RunPython(limpiar_iconos, revertir),
    ]
