# Generated by Django 5.2.5 on 2026-08-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0005_alter_categoria_color_alter_categoria_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstruccionesEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(blank=True, help_text='Lugar, horario, oficina o cualquier indicación para la entrega.', verbose_name='Instrucciones para reclamar el objeto')),
                ('fecha_actualizada', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Instrucciones de entrega',
                'verbose_name_plural': 'Instrucciones de entrega',
            },
        ),
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='apelacion',
            field=models.TextField(blank=True, verbose_name='Motivo de la apelación'),
        ),
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='comentario_admin',
            field=models.TextField(blank=True, help_text='Motivo de la decisión que verá el estudiante.', verbose_name='Comentario del administrador'),
        ),
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='fecha_apelacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de apelación'),
        ),
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='fue_apelada',
            field=models.BooleanField(default=False, verbose_name='¿Fue apelada?'),
        ),
        migrations.AlterField(
            model_name='solicitudreclamacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('apelada', 'Apelada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
