# Generated by Django 5.2.5 on 2026-08-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0006_instruccionesentrega_solicitudreclamacion_apelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='respuesta_vista',
            field=models.BooleanField(default=True, help_text='Se marca como no vista cuando hay una respuesta nueva del admin.', verbose_name='¿Respuesta vista por el estudiante?'),
        ),
    ]
