# Generated by Django 5.2.5 on 2026-08-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0007_solicitudreclamacion_respuesta_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='datos_entrega',
            field=models.TextField(blank=True, help_text='Información específica de esta entrega (lugar, horario). Se muestra al estudiante al aprobar; si está vacía se usa el texto general de configuración.', verbose_name='Datos para reclamar el objeto'),
        ),
    ]
