# Generated by Django 5.2.5 on 2026-08-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0008_solicitudreclamacion_datos_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetoreclamado',
            name='sede',
            field=models.CharField(choices=[('minas', 'Sede Minas'), ('volador', 'Sede El Volador')], db_index=True, default='minas', help_text='Sede donde se encontró o se entrega el objeto.', max_length=20, verbose_name='Sede'),
        ),
    ]
