# Generated by Django 5.2.5 on 2026-08-30 22:33

from django.db import migrations, models


def copiar_texto_a_sedes(apps, schema_editor):
    InstruccionesEntrega = apps.get_model('registro_objetos', 'InstruccionesEntrega')
    for config in InstruccionesEntrega.objects.all():
        texto = config.texto or ''
        config.texto_minas = texto
        config.texto_volador = texto
        config.save(update_fields=['texto_minas', 'texto_volador'])


def copiar_texto_minas_a_texto(apps, schema_editor):
    InstruccionesEntrega = apps.get_model('registro_objetos', 'InstruccionesEntrega')
    for config in InstruccionesEntrega.objects.all():
        config.texto = config.texto_minas or ''
        config.save(update_fields=['texto'])


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0010_categoria_iconos'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruccionesentrega',
            name='texto_minas',
            field=models.TextField(blank=True, help_text='Lugar, horario, oficina o cualquier indicación para reclamar un objeto en la Sede Minas.', verbose_name='Instrucciones · Sede Minas'),
        ),
        migrations.AddField(
            model_name='instruccionesentrega',
            name='texto_volador',
            field=models.TextField(blank=True, help_text='Lugar, horario, oficina o cualquier indicación para reclamar un objeto en la Sede El Volador.', verbose_name='Instrucciones · Sede El Volador'),
        ),
        migrations.RunPython(
            copiar_texto_a_sedes,
            reverse_code=copiar_texto_minas_a_texto,
        ),
        migrations.RemoveField(
            model_name='instruccionesentrega',
            name='texto',
        ),
        migrations.AlterField(
            model_name='solicitudreclamacion',
            name='datos_entrega',
            field=models.TextField(blank=True, help_text='Información específica de esta entrega (lugar, horario). Se muestra al estudiante al aprobar; si está vacía se usa el texto configurado para la sede.', verbose_name='Datos para reclamar el objeto'),
        ),
    ]