# Generated by Django 5.2.5 on 2026-08-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0011_remove_instruccionesentrega_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='firma',
            field=models.ImageField(blank=True, help_text='Imagen PNG con fondo transparente. Se estampa en los formatos de entrega que genere este encargado.', null=True, upload_to='firmas/', verbose_name='Firma digital (administradores)'),
        ),
    ]
