# Generated by Django 5.2.5 on 2026-08-31 01:09

from django.db import migrations, models


def normalizar_tipos_documento(apps, schema_editor):
    """Convierte los valores históricos en texto libre a los códigos CC/TI/CE."""
    ObjetoReclamado = apps.get_model('registro_objetos', 'ObjetoReclamado')
    equivalencias = {
        'Cédula de ciudadanía': 'CC',
        'Tarjeta de identidad': 'TI',
        'Cédula de extranjería': 'CE',
    }
    for objeto in ObjetoReclamado.objects.exclude(tipo_documento__in=['', 'CC', 'TI', 'CE']):
        objeto.tipo_documento = equivalencias.get(str(objeto.tipo_documento).strip(), '')
        objeto.save(update_fields=['tipo_documento'])


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0012_perfilusuario_firma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objetoreclamado',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='objetoreclamado',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería')], default='', max_length=50, verbose_name='Tipo de documento'),
        ),
        migrations.RunPython(normalizar_tipos_documento),
    ]
