# Generated by Django 5.2.5 on 2026-09-01 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0013_alter_objetoreclamado_fecha_registro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='entregado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Entregado por'),
        ),
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='formato_descargado',
            field=models.BooleanField(default=False, verbose_name='¿Formato descargado?'),
        ),
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de documento'),
        ),
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='solicitudreclamacion',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('CC', 'Cédula de ciudadanía'), ('TI', 'Tarjeta de identidad'), ('CE', 'Cédula de extranjería'), ('PEP', 'Pasaporte')], max_length=10, verbose_name='Tipo de documento'),
        ),
    ]
