# Generated by Django 5.2.5 on 2026-09-03 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_objetos', '0014_solicitudreclamacion_entregado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetoreclamado',
            name='foto_base64',
            field=models.TextField(blank=True, default='', verbose_name='Foto (base64)'),
        ),
    ]
